#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='nano'
export VISUAL='nano'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi

# Python installs binaries to /usr/local/share/python.
PATH="/usr/local/share/python:$PATH";  export PATH
PYTHONPATH="/usr/local/lib/python2.7/site-packages"; export PYTHONPATH

# User-local binaries.
PATH="$HOME/bin:$PATH"; export PATH

alias be='bundle exec'
alias livestreamer='/usr/local/bin/livestreamer --player /Applications/VLC.app/Contents/MacOS/VLC'
alias youtube-dl='youtube-dl --title --continue'
alias z='fasd_cd -d'

# A "find-by-insensitive-filename" helper. Provide a single argument to search for files
# whose name contain the substring, or two parameters if you want to specify a directory in
# which to search:
#
#   ifind substring
#   ifind directory substring
function ifind () {
  if [ "$2" != "" ]
  then
    find $1 -iname "*$2*"
  else
    find . -iname "*$1*"
  fi
}
