#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export GIT_EDITOR='vim +1 -c start'
export BUNDLER_EDITOR='mvim'

export PAGER='less'

# /usr/bin/local for Vundle.
PATH="/usr/local/bin:/usr/local/sbin:$PATH"; export PATH

# rbenv
PATH="$HOME/.rbenv/bin:$PATH"; export PATH

# Default JRuby to 1.9 mode.
JRUBY_OPTS=--1.9

eval "$(rbenv init - 2>&-)"
